### PR TITLE
libcflib v0.0.8

### PR DESCRIPTION
**Pull request by scopatz**
Merge only after success.

This pull request was auto-generated by [rever](https://regro.github.io/rever-docs/)

### CODE REVIEW

**Comment by scopatz** [comment]
@conda-forge-admin please rerender

**Comment by CJ-Wright** [comment]
Is it odd that defaults numpy is being dragged into this?

**Comment by scopatz** [comment]
Yeah the defaults numpy thing is weird, but the actual error is xonsh. Should have a new release relatively soon.

**Comment by scopatz** [comment]
@conda-forge-admin please rerender

**Pull request merged**
